name: GHA_Lab_02_Secrets_Terraform Deployment with Github

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  Deploy_SG:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform-sg
    env:
      # AWS_REGION: us-west-2; using via GH secrets
      TF_BACKEND_CONFIG: -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}"
      TF_WORKING_DIR: ./terraform-sg
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region:  ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # - name: Terraform fmt
      #   id: fmt
      #   run: terraform fmt -check
      #   continue-on-error: true

      - name: Terraform Init
        run: terraform init ${{ env.TF_BACKEND_CONFIG }}
        # run: terraform -chdir=${{ env.TF_WORKING_DIR }} init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan ${{ env.TF_BACKEND_CONFIG }}
        # run: terraform -chdir=${{ env.TF_WORKING_DIR }} plan

      - name: Terraform Apply
        run: terraform apply -auto-approve ${{ env.TF_BACKEND_CONFIG }}
      #   run: terraform -chdir=${{ env.TF_WORKING_DIR }} apply -auto-approve